#!/bin/sh

#SBATCH --job-name=A_hex

#SBATCH --output=A.o

#SBATCH --error=A.error

#SBATCH --partition=savio

#SBATCH --time=400:00:00

#SBATCH --nodes=4

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=20

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=yves.robert@insa-lyon.fr
#SBATCH --mail-type=all

# run command
setenv OMP_NUM_THREAD 20

mpirun -np 4 --map-by ppr:1:node:pe=20 sss2 -omp 20 A
