#!/bin/sh

#SBATCH --job-name=A_hex

#SBATCH --output=A.o

#SBATCH --error=A.error

#SBATCH --partition=savio

#SBATCH --time=400:00:00

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=20

# QoS:

#SBATCH --qos=savio_normal

#

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=yves.robert@insa-lyon.fr
#SBATCH --mail-type=all

# run command
setenv OMP_NUM_THREAD 24

sss2 -omp 24 A
